name: Bug report
description: Create a report to help us improve
title: "[BUG] "
labels:
  - bug
type: bug
body:
  # Describe the bug
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: When doing X, I expected Y, but Z happened instead
    validations:
      required: true

  # How to reproduce the bug
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the unexpected behaviour
      placeholder: | 
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. Press these keys '...'
        5. See error
      render: markdown
    validations:
      required: true

  # Error log
  - type: textarea
    id: traceback
    attributes:
      label: Error Log
      description: If applicable, add the traceback here
      render: console
    validations:
      required: false

  # Expected behaviour
  - type: textarea
    id: expectation
    attributes:
      label: Expected Behaviour
      description: A clear and concise description of what you expected to happen
    validations:
      required: true

  # Screenshots
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop the screenshots here
    validations:
      required: false

  # Additional context
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one option
      options:
        - label: macOS
        - label: Windows
        - label: Linux
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here
    validations:
      required: false
