name: Feature request
description: Create a request for new features
title: "[FEATURE] "
labels:
  - enhancement
type: feature
body:
  # Describe the feature
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of what is being requested
      placeholder: Add your description here
    validations:
      required: true

  # Use case
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why is this important and where is it applicable?
      placeholder: Add your use case here
    validations:
      required: true

  # Expected behaviour
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: A clear and concise description of what you expect to happen
      placeholder: Add your expected behaviour here
    validations:
      required: true

  # Screenshots
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots/Mockups
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop the screenshots here
    validations:
      required: false

  # Additional context
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one option
      options:
        - label: macOS
        - label: Windows
        - label: Linux
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here
    validations:
      required: false
